language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: linux
      dist: precise
      r: 3.2
    - os: linux
      dist: xenial
#      r_check_args: '--use-valgrind'
    - os: osx
      brew_packages: openssl
      after_success: R -e 'covr::codecov()'
    - os: osx
      brew_packages: openssl@1.1
      before_install: brew uninstall --ignore-dependencies openssl
      env: PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
    - os: osx
      brew_packages: libressl
      before_install: brew uninstall --ignore-dependencies openssl openssl@1.1
      env: PKG_CONFIG_PATH="/usr/local/opt/libressl/lib/pkgconfig"
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
    - os: osx
      disable_homebrew: true

addons:
  apt:
    packages:
    - libssl-dev
    - valgrind

r_packages: covr

notifications:
  email:
    on_success: change
    on_failure: change
