language: r
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libssl-dev

r_github_packages:
  - jimhester/covr
  - jeroenooms/openssl #for jose
  - jeroenooms/jose

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
