language: r
cache: packages
latex: false
fortran: false

r_check_args: ' '

matrix:
  include:
    - dist: xenial
      r: 3.2
    - dist: bionic
    - os: osx
      brew_packages: openssl@1.1
      before_install: brew uninstall --ignore-dependencies openssl
      env: PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
    - os: osx
      brew_packages: libressl
      before_install: brew uninstall --ignore-dependencies openssl@1.1
      env: PKG_CONFIG_PATH="/usr/local/opt/libressl/lib/pkgconfig"
    - r: 3.6
      os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
    - os: osx
      disable_homebrew: true

addons:
  apt:
    packages:
    - libssl-dev
    - libsodium-dev
