language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
      sudo: required
    - os: osx
      osx_image: xcode8.3
      brew_packages: openssl@1.1
      latex: false
    - os: osx
      osx_image: xcode8.3
      brew_packages: openssl
      latex: false
    - os: osx
      osx_image: xcode8.3
      brew_packages: libressl
      latex: false
    - os: osx
      osx_image: xcode8.3
      brew_packages: domt4/crypto/boringssl
      latex: false
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      latex: false

addons:
  apt:
    packages:
    - libssl-dev
    - valgrind

r_github_packages:
  - jeroenooms/jsonlite
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
